namespace RJCP.Native.Win32
{
    internal partial class WinIoCtl
    {
        public enum DeviceType
        {
            Beep = 1,
            CdRom = 2,
            CdRomFileSystem = 3,
            Controller = 4,
            DataLink = 5,
            Dfs = 6,
            Disk = 7,
            DiskFileSystem = 8,
            FileSystem = 9,
            InportPort = 10,
            Keyboard = 11,
            MailSlot = 12,
            MidiIn = 13,
            MidiOut = 14,
            Mouse = 15,
            MultiUncProvider = 16,
            NamedPipe = 17,
            Network = 18,
            NetworkBrowser = 19,
            NetworkFileSystem = 20,
            Null = 21,
            ParallelPort = 22,
            PhysicalNetCard = 23,
            Printer = 24,
            Scanner = 25,
            SerialMousePort = 26,
            SerialPort = 27,
            Screen = 28,
            Sound = 29,
            Streams = 30,
            Tape = 31,
            TapeFileSystem = 32,
            Transport = 33,
            Unknown = 34,
            Video = 35,
            VirtualDisk = 36,
            WaveIn = 37,
            WaveOut = 38,
            Device8042Port = 39,
            NetworkRedirector = 40,
            Battery = 41,
            BusExtender = 42,
            Modem = 43,
            Vdm = 44,
            MassStorage = 45,
            Smb = 46,
            Ks = 47,
            Changer = 48,
            SmartCard = 49,
            Acpi = 50,
            Dvd = 51,
            FullScreenVideo = 52,
            DfsFileSystem = 53,
            DfsVolume = 54,
            SerEnum = 55,
            TermSrv = 56,
            KSec = 57,
            Fips = 58,
            Infiniband = 59,
            VmBus = 62,
            CryptProvider = 63,
            Wpd = 64,
            Bluetooth = 65,
            MtComposite = 66,
            MtTransport = 67,
            Biometric = 68,
            Pmi = 69,
            EHStor = 70,
            DevApi = 71,
            Gpio = 72,
            UsbEx = 73,
            Console = 80,
            Nfp = 81,
            SysEnv = 82,
            VirtualBlock = 83,
            PointOfService = 84,
            StorageReplication = 85,
            TrustEnv = 86,
            Ucm = 87,
            UcpTcpci = 88,
            PersistentMemory = 89,
            NVDimm = 90,
            Holographic = 91,
            SdfXhci = 92,
            UcmUcsi = 93,

            MountMgr = 'm',
            MountMgrDevice = 'M',
            Volume = 'V'
        }
    }
}
